import type {Metadata} from 'next';
import './globals.css';
import Providers from '@/store/Providers';
import {ToastContainer} from 'react-toastify';
import {Footer} from "antd/es/layout/layout";
import AuthGuard from "@/components/AuthGuard";
import GlobalChat from "@/components/GlobalChat";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className="flex flex-col min-h-screen">
        <Providers>
            <AuthGuard>
                <main className="flex-grow">{children}</main>
            </AuthGuard>
            <GlobalChat/>
            <Footer/>
            <ToastContainer/>
        </Providers>
        </body>
        </html>
    );
}