import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Providers from '@/store/Providers';
import { ToastContainer } from 'react-toastify';
import PageLoader from "@/app/layout/pageLoader";
import {Footer} from "antd/es/layout/layout";
import {Header} from "antd/lib/layout/layout";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <body className="flex flex-col min-h-screen">
      <Providers>
        <Header />
        <main className="flex-grow">{children}</main>
        <Footer />
        <ToastContainer />
      </Providers>
      </body>
      </html>
  );
}